if: tag IS blank
language: node_js
node_js:
  - "lts/*"
  - "node"
script: npm run ci

stages:
  - test
  - name: publish
    if: branch in (master, v19) && type != pull_request

jobs:
  include:
    - stage: publish
      node_js: node
      script:
        - sh build.sh
        - git remote set-url origin https://${GITHUB_TOKEN}@github.com/WTW-IM/es-components.git
        - git checkout ${TRAVIS_BRANCH}
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
        - npx lerna publish --conventional-commits --changelog-preset conventional-changelog-eslint --yes
        - sh rebuild-docs.sh
      deploy:
        - provider: pages
          skip-cleanup: true
          github-token: $GITHUB_TOKEN
          keep-history: true
          local-dir: ./packages/es-components/docs