name: CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test:
    name: Test with Node v${{matrix.node}}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node Version
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - name: Install Dependencies
        run: |
          cd packages/es-components/
          npm ci
          cd ../..
      - name: Run Tests
        run: |
          cd packages/es-components/
          npm run ci
          cd ../..

  npm_prerelease:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: test
    name: Pre-Prod Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.IM_PIPELINE_BOT_TOKEN }}
          ref: pre-prod
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          npm ci
          cd packages/es-components
          npm ci
          cd ../..
      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"
      - name: Merge master to pre-prod
        run: |
          git merge --no-verify -Xtheirs --commit origin/master -m "Merging master into pre-prod [skip-release]"
          # abort if failed merge
          git merge --abort || true
          git push origin pre-prod
      # This is so that we always update the pre-prod dist tag with master when we merge.
      # (Pre-prod can be ahead of master, but never behind.)
      - name: Lerna Publish Pre-Prod
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          npx lerna publish --conventional-commits --changelog-preset @aabenoja/conventional-changelog-eslint-lerna --conventional-prerelease --dist-tag pre-prod --preid pre-prod --allow-branch pre-prod --yes

  npm:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: [test, npm_prerelease]
    name: Publish NPM Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.IM_PIPELINE_BOT_TOKEN }}
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          npm ci
          cd packages/es-components
          npm ci
          cd ../..
      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"
      - name: Lerna Publish Latest
        run: |
          echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}" > ~/.npmrc
          npx lerna publish --conventional-commits --changelog-preset @aabenoja/conventional-changelog-eslint-lerna --conventional-graduate --yes

  docs:
    if: ${{ github.ref == 'refs/heads/master' }}
    needs: npm
    name: Publish Docs to GH Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.IM_PIPELINE_BOT_TOKEN }}
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          cd packages/es-components
          npm ci
          cd ../..
      - name: Set Commitbot Identity
        run: |
          git config user.name "ES-Components Lerna Publish Bot"
          git config user.email "es-components-bot@wtw.org"
      - name: Rebuild docs
        run: |
          npm run --prefix ./packages/es-components styleguide-build
      - name: Publish docs to github pages
        run: |
          git checkout gh-pages
          rm -rf build/
          mv ./packages/es-components/docs/* .
          git add index.html full-color-icons.html full-color-icons.js build
          git commit -m "Deploy es-component docs to gh-pages"
          git push origin gh-pages
